import re
import os

translations = {
    "ready": "Ready",
    "regenerate_on_launch": "Regenerate on launch",
    "requires_sensitive_permissions": "Requires sensitive permissions",
    "reset_env_confirm": "Resetting the environment will clear all build cache. Proceed?",
    "reset_environment": "Reset Environment",
    "retry": "Retry",
    "run": "Run",
    "sample_projects": "Sample Projects",
    "save": "Save",
    "save_as_scheme": "Save as Scheme",
    "save_lrc": "Save LRC",
    "saved": "Saved",
    "scanning_project": "Scanning project...",
    "scheme_name": "Scheme Name",
    "search_code_snippets": "Search code snippets...",
    "search_modules": "Search modules...",
    "search_modules_hint": "Search by name or description...",
    "search_placeholder": "Search...",
    "secondary_color": "Secondary Color",
    "select_extension_modules": "Select extension modules",
    "select_file": "Select File",
    "select_files": "Select Files",
    "select_files_hint": "Select HTML, CSS, JS etc. (CSS/JS optional)",
    "select_folder": "Select Folder",
    "select_icon": "Select Icon",
    "select_image": "Select Image",
    "select_launch_time": "Select launch time",
    "select_media_type": "Select media type",
    "select_module_category": "Select module category",
    "select_modules": "Select modules",
    "select_music": "Select music",
    "select_project": "Select project",
    "select_project_folder": "Select project folder",
    "select_project_hint": "Select project build output directory (e.g., dist/build)",
    "select_theme": "Select theme",
    "select_ui_style": "Select UI style",
    "select_ui_style_hint": "Choose interface style",
    "select_video": "Select video",
    "select_wtamod_file": "Select .wtamod or .wtapkg file",
    "selected_duration": "Duration: %.1f s",
    "selected_image": "Selected image",
    "selected_music_count": "Selected %d items",
    "sequential_playback": "Sequential playback",
    "share": "Share",
    "share_code": "Share code",
    "share_code_copied": "Share code copied",
    "share_module": "Share module",
    "show_emoji": "Show emoji",
    "show_once": "Show once only",
    "show_once_only": "Show once only",
    "shuffle_playback": "Shuffle playback",
    "social_media": "Social media",
    "sound_feedback": "Sound feedback",
    "sound_feedback_hint": "Interaction sound feedback (vibration)",
    "splash_screen": "Splash screen",
    "standard_encryption": "Standard",
    "start_test": "Start test",
    "static_website": "Static website",
    "status_bar_background": "Status bar bg",
    "storage_isolation": "Storage isolation",
    "storage_permission_required": "Storage permission required",
    "storage_usage": "Storage usage",
    "store_get_download_link_failed": "Get download link failed: %1$s",
    "store_network_error": "Network error: %1$s",
    "store_report_failed": "Report failed: %1$s",
    "success": "Success",
    "suggestions": "Suggestions",
    "support_vue_react_vite": "Support Vue, React, Vite build output",
    "supported_features": "Supported features",
    "tags": "Tags",
    "tags_hint": "Tags, e.g., tool, efficiency",
    "tap_to_mark": "Tap to mark",
    "tech_description": "Tech description",
    "test_module": "Test module",
    "theme": "Theme",
    "theme_dark": "Dark theme",
    "theme_features": "Theme features",
    "theme_light": "Light theme",
    "theme_settings_title": "Theme settings",
    "thinking": "Thinking",
    "thinking_dots": "Thinking...",
    "title_create_app": "Create App",
    "title_my_apps": "My Apps",
    "title_settings": "Settings",
    "too_many_attempts_with_countdown": "Too many attempts. Retry after %1$s",
    "total_duration_label": "Duration: %.1f s",
    "total_files": "Total %d files",
    "total_files_count": "Total %d files",
    "total_modules": "Total %d modules",
    "translate_enabled": "Translate enabled",
    "translate_target_language": "Target language",
    "translate_to": "Translate to",
    "trim_range_hint": "Trim range (seconds)",
    "ui_mode": "UI Mode",
    "unknown_error": "Unknown error",
    "unknown_file": "Unknown file",
    "update_later": "Later",
    "update_now": "Now",
    "upload": "Upload",
    "url_to_shortcut_basic": "URL to shortcut basic",
    "usage_access_not_enabled": "Usage access not enabled",
    "usage_help": "Usage help",
    "usage_steps": "Usage steps",
    "usage_steps_content": "1. Run build command: npm run build\\n2. Select build output (dist/build)\\n3. Generate app",
    "user_agent_spoofing": "User Agent spoofing",
    "version": "Version",
    "version_code": "Version code",
    "version_code_label": "Version code",
    "version_name": "Version name",
    "version_name_label": "Version name",
    "video": "Video",
    "video_app": "Video app",
    "video_file_not_exist": "Video file not found",
    "video_preview": "Video preview",
    "help_model_selection": "Model Selection",
    "help_model_selection_content": "Choose different AI models for code generation, each with varying speed and effect.",
    "help_requirement_tips": "Tips for requirements",
    "help_requirement_tips_content": "• Describe specific functions\\n• Specify the target site or page type\\n• Refer to example requirements",
    "help_save_module": "Save Module",
    "help_save_module_content": "Once generation is complete, click \"Save\" to add it to your module library for future use.",
    "high_perf_build_tool": "High-performance Build Tool",
    "hold_to_experience": "Hold to Experience",
    "html_app": "HTML App",
    "html_app_tip": "Tip: HTML is required, CSS and JS are optional. If your HTML references them, please select those files as well.",
    "html_file": "HTML File",
    "i_understand": "I Understand",
    "icon_library": "Icon Library",
    "image": "Image",
    "image_app": "Image App",
    "import_data": "Import Data",
    "import_from_file": "Import from File",
    "import_from_share_code": "Import from Share Code",
    "import_frontend_project": "Import Frontend Project",
    "import_logs": "Import Logs",
    "import_module": "Import Module",
    "import_project": "Import Project",
    "import_text": "Import",
    "importing": "Importing...",
    "independent_developer": "Independent Developer • AI Generated",
    "info": "Info",
    "input_activation_code_hint": "Enter activation code",
    "input_app_name": "Please enter app name",
    "input_module_name": "Please enter module name",
    "input_scheme_name": "Please enter scheme name",
    "install_advanced_build_tool": "Install advanced build tool (esbuild)",
    "installed": "Installed",
    "installing_deps": "Installing dependencies...",
    "interaction_method": "Interaction Method",
    "interaction_style": "Interaction Style",
    "interaction_style_label": "Interaction style: %s",
    "international_email": "Email Contact",
    "international_group": "International Group",
    "invalid_activation_code": "Invalid activation code",
    "invalid_format": "Invalid Format",
    "invalid_time_limit_config": "Invalid time limit config",
    "invalid_usage_limit_config": "Invalid usage limit config",
    "ip_spoofing": "IP Spoofing",
    "isolation_hint": "Enable environment isolation",
    "isolation_settings": "Isolation Settings",
    "join_exchange_group": "Join Exchange Group",
    "js_file": "JavaScript File",
    "key_name_hint": "e.g., fontSize",
    "key_name_required": "Key Name *",
    "label_activation": "Activation Code",
    "label_ad_block": "Ad Blocking",
    "label_ads": "Ads Settings",
    "label_announcement": "Announcement",
    "label_app_name": "App Name",
    "label_icon": "App Icon",
    "label_url": "Website URL",
    "landscape_mode": "Landscape Mode",
    "landscape_mode_hint": "Force landscape orientation",
    "landscape_mode_hint_html": "Recommended for games/video",
    "landscape_mode_label": "Landscape",
    "language_arabic": "Arabic",
    "language_changed": "Language changed, please restart app",
    "language_chinese": "Chinese",
    "language_english": "English",
    "language_settings": "Language",
    "latest_version": "Latest version",
    "launch_time": "Launch time",
    "learn_progress_together": "Learn and progress together, update news etc.",
    "light_mode": "Light mode",
    "light_mode_hint": "Always use light theme",
    "link_button_text": "Link button text",
    "link_url": "Link URL (optional)",
    "load_image_failed": "Load image failed: %s",
    "loading": "Loading...",
    "logs": "Logs",
    "loop_play": "Loop play",
    "loop_play_hint": "Loop play video/audio",
    "loop_playback": "Loop playback",
    "manual_create": "Manual create",
}

path = r"app\src\main\res\values\strings.xml"

# Try different encodings
encodings = ['utf-8', 'utf-8-sig', 'gb18030', 'gbk', 'latin-1']

content = None
chosen_encoding = None

for enc in encodings:
    try:
        with open(path, 'r', encoding=enc) as f:
            content = f.read()
            chosen_encoding = enc
            print(f"Successfully read with {enc}")
            break
    except UnicodeDecodeError:
        continue

if content is None:
    # Fallback to errors='replace'
    with open(path, 'r', encoding='utf-8', errors='replace') as f:
        content = f.read()
        chosen_encoding = 'utf-8'
        print("Read with utf-8 and errors='replace'")

lines = content.splitlines(keepends=True)
new_lines = []
for line in lines:
    match = re.search(r'<string name="([^"]+)"', line)
    if match:
        name = match.group(1)
        if name in translations:
            line = re.sub(r'>(.*?)</string>', f'>{translations[name]}</string>', line)
    new_lines.append(line)

with open(path, 'w', encoding='utf-8') as f:
    f.writelines(new_lines)

print("Done translating strings.xml")
